// Generated by gencpp from file custom_messages/play_poseResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_PLAY_POSERESPONSE_H
#define CUSTOM_MESSAGES_MESSAGE_PLAY_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct play_poseResponse_
{
  typedef play_poseResponse_<ContainerAllocator> Type;

  play_poseResponse_()
    : play_res(0.0)  {
    }
  play_poseResponse_(const ContainerAllocator& _alloc)
    : play_res(0.0)  {
  (void)_alloc;
    }



   typedef float _play_res_type;
  _play_res_type play_res;





  typedef boost::shared_ptr< ::custom_messages::play_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::play_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct play_poseResponse_

typedef ::custom_messages::play_poseResponse_<std::allocator<void> > play_poseResponse;

typedef boost::shared_ptr< ::custom_messages::play_poseResponse > play_poseResponsePtr;
typedef boost::shared_ptr< ::custom_messages::play_poseResponse const> play_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::play_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::play_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::play_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::play_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::play_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::play_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::play_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::play_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::play_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b61e27d22960a887012b295e26e4ccc";
  }

  static const char* value(const ::custom_messages::play_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b61e27d22960a88ULL;
  static const uint64_t static_value2 = 0x7012b295e26e4cccULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::play_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/play_poseResponse";
  }

  static const char* value(const ::custom_messages::play_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::play_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 play_res\n\
\n\
";
  }

  static const char* value(const ::custom_messages::play_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::play_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.play_res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct play_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::play_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::play_poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "play_res: ";
    Printer<float>::stream(s, indent + "  ", v.play_res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_PLAY_POSERESPONSE_H
